import {
    ScrollView,
    FText,
} from "../../../../senders/ui-components/std-widgets.slint";
import { Bridge } from "globals.slint";

component OutlinedText inherits FText {
    stroke-width: 2px;
    stroke: black;
    font-size: 22px;
    color: white;
}

export component DebugOverlay inherits Rectangle {
    x: 0;
    y: 0;

    ScrollView {
        VerticalLayout {
            padding: 8px;
            spacing: 10px;

            OutlinedText {
                text: "Connected devices: " + Bridge.connected_devices //
                + "  Volume: " + Bridge.volume //
                + "  Is playing: " + (Bridge.playing ? "true" : "false") //
                + "  Playback state: " + Bridge.gui-playback-state-to-string(Bridge.playback-state) //
                + "  Progress label: " + Bridge.progress-label
                + "  Is live: " + (Bridge.is-live ? "true" : "false");
                wrap: word-wrap;
            }
        }
    }
}
