import {
    Icons,
    FText,
    ScrollView,
    Spinner,
    Button,
    Palette,
    ListView,
    Slider,
} from "../../../../senders/ui-components/std-widgets.slint";
import { FCastPalette } from "../../../../senders/ui-components/styling.slint";
import "../../../../senders/ui-components/fonts/Outfit-Regular.ttf";
import {
    Bridge,
    GuiPlaybackState,
    AppState,
    UiPlayerVariant,
} from "globals.slint";
import { IdleView } from "views/idle.slint";
import { LoadingMediaView } from "views/loading-media.slint";
import { VideoPlayerView } from "views/video-player.slint";
import { ImageView } from "views/image.slint";
import { AudioPlayerView } from "views/audio-player.slint";
import { RaopView } from "views/raop.slint";
import { ToastOverlay } from "toast-overlay.slint";

export {
    Bridge,
    GuiPlaybackState,
    AppState,
    UiPlayerVariant,
}

export component MainWindow inherits Window {
    title: "FCast Receiver";

    default-font-family: "Outfit";
    default-font-size: 15px;
    default-font-weight: 400;

    public function device-connected() {
        Bridge.connected_devices += 1;
    }

    FocusScope {
        capture-key-pressed(event) => Bridge.capture-key-pressed(event);
    }

    // TODO:
    // Rectangle {
    //     x: root.safe-area-insets.left;
    //     y: root.safe-area-insets.top;
    //     width: root.width - root.safe-area-insets.right - root.safe-area-insets.left;
    //     height: root.height - root.safe-area-insets.bottom - root.safe-area-insets.top;
    // }

    if Bridge.app-state == AppState.Idle: IdleView { }

    if Bridge.app-state == AppState.LoadingMedia: LoadingMediaView { }

    if Bridge.app-state == AppState.Playing && Bridge.player-variant == UiPlayerVariant.Video: VideoPlayerView { }

    if Bridge.app-state == AppState.Playing && Bridge.player-variant == UiPlayerVariant.Image: ImageView { }

    if Bridge.app-state == AppState.Playing && Bridge.player-variant == UiPlayerVariant.Audio: AudioPlayerView { }

    if Bridge.app-state == AppState.Playing && Bridge.player-variant == UiPlayerVariant.Raop: RaopView { }

    if Bridge.should-show-toast-overlay(): ToastOverlay { }
}
