import {
    FText,
} from "../../../../senders/ui-components/std-widgets.slint";
import {
    Bridge,
} from "globals.slint";

enum ToastVariant {
    Error,
    Warning,
}

component Toast inherits Rectangle {
    in property <ToastVariant> variant;
    in property <string> message;

    background: @linear-gradient(90.17deg, rgba(255, 255, 255, 0.1) 0.15%, rgba(255, 255, 255, 0.03) 85%);
    border-radius: self.height / 2;
    border-width: 1px;
    border-color: @linear-gradient(153.5deg, rgba(255, 255, 255, 0.1) 7.41%, rgba(255, 255, 255, 0.031) 27.47%, rgba(255, 255, 255, 0.1) 52.75%, rgba(255, 255, 255, 0.03) 73.25%, rgba(255, 255, 255, 0.1) 94.61%);

    HorizontalLayout {
        alignment: center;
        padding: 16px;
        spacing: 10px;

        VerticalLayout {
            alignment: center;

            Rectangle {
                width: t.width;
                height: t.height;

                t := Image {
                    source: @image-url("warning-triangle.svg");

                    states [
                        error when variant == ToastVariant.Error: {
                            colorize: @linear-gradient(140.89deg, #F44F5A 15.72%, #EE3D4A 46.23%, #E52030 84.58%);
                        }
                        warning when variant == ToastVariant.Warning: {
                            colorize: @linear-gradient(140.89deg, #fdb022 15.72%, #fdb022 46.23%, #fdb022 84.58%);
                        }
                    ]
                }

                Image {
                    source: @image-url("exclamation-mark.svg");
                    width: 35px;
                }
            }
        }

        FText {
            text: message;
            wrap: word-wrap;
            vertical-alignment: center;
        }
    }
}

export component ToastOverlay inherits Rectangle  {
    VerticalLayout {
        pure function compute-width(available: length) -> length {
            Math.min(available, error-rect.preferred-width + self.padding * 2)
        }

        width: compute-width(root.width > 700px ? 700px : root.width);
        padding: 20px;

        error-rect := VerticalLayout {
            spacing: 15px;

            if Bridge.is-showing-error-message: HorizontalLayout {
                alignment: center;

                Toast {
                    variant: Error;
                    message: Bridge.error-message;
                }
            }

            if Bridge.is-showing-warning-message: HorizontalLayout {
                alignment: center;

                Toast {
                    variant: Warning;
                    message: Bridge.warning-message;
                }
            }
       }

        Rectangle {}
    }

    Timer {
        interval: 4s;
        running: Bridge.is-showing-error-message;
        triggered() => {
            Bridge.is-showing-error-message = false;
            Bridge.error-message = "";
        }
    }

    Timer {
        interval: 4s;
        running: Bridge.is-showing-warning-message;
        triggered() => {
            Bridge.is-showing-warning-message = false;
            Bridge.warning-message = "";
        }
    }
}

