[package]
name = "receiver-android"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]
rcore = { package = "receiver-ui", path = "../../../crates/receiver-ui", features = ["android"] }
android_logger = "0.15.1"
log-panics = { version = "2.1.0", features = ["with-backtrace"]}
log.workspace = true
jni = "0.21.1"
ndk-context = "0.1.1"
tokio.workspace = true
parking_lot.workspace = true

[lib]
name = "fcastreceiver"
crate-type = ["cdylib"]