[package]
name = "receiver-android"
version = "0.1.0"
edition = "2024"

[dependencies]
rcore = { package = "receiver-ui", path = "../../../crates/receiver-ui", features = ["android"] }
env_logger.workspace = true
# common = { path = "../common" }
anyhow.workspace = true
android_logger = "0.15.1"
log-panics = { version = "2.1.0", features = ["with-backtrace"]}
log.workspace = true
jni = "0.21.1"
tokio.workspace = true
parking_lot.workspace = true

[lib]
name = "fcastreceiver"
crate-type = ["cdylib"]