
# Run command: `cirrus run buildReceiverMac --artifacts-dir receivers/electron/out`
build_electron_receiver_task:
  name: buildReceiverMac
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:14.3.1
  buildReceiverMac_script:
    # Local
    # - source .secure_files/.env

    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - sudo security add-certificates -k /Library/Keychains/System.keychain ./.secure_files/developerID_application.cer
    - security unlock-keychain -p "admin" ~/Library/Keychains/login.keychain
    - security import ./.secure_files/Certificates.p12 -k ~/Library/Keychains/login.keychain -P "$FCAST_CERTIFICATES_PASSWORD" -T /usr/bin/codesign
    # Keychain ignores access control, causing to prompt for access and failing in CI environments...: https://stackoverflow.com/a/40039594
    - "security set-key-partition-list -S apple-tool:,apple: -s -k admin ~/Library/Keychains/login.keychain"

    - mkdir -p ~/.ssh/
    - cp ./.secure_files/id_ed25519 ~/.ssh/id_ed25519
    - cp ./.secure_files/id_ed25519.pub ~/.ssh/id_ed25519.pub
    - chmod 700 ~/.ssh/
    - chmod 600 ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519.pub

    - cd receivers/electron
    - npm install
    - npm rebuild
    - npm run build
    - npm run make -- --platform="darwin" --arch="arm64"
    - npm run make -- --platform="darwin" --arch="x64"
    - scp -o StrictHostKeyChecking=no -r out/make/* root@$FCAST_DO_RUNNER_IP:/artifacts/
    - tar -czf artifacts.tar out/make/
  binary_artifacts:
    path: receivers/electron/artifacts.tar

desktop_sender_task:
  name: buildSenderMacosArm64
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:14.3.1
  buildReceiverMac_script:
    - brew install rustup-init protobuf wget
    - rustup-init -y
    - rustup target add aarch64-apple-darwin
    - source $HOME/.cargo/env

    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash

    # Download and install gstreamer
    - wget -q "https://gstreamer.freedesktop.org/data/pkg/osx/1.26.8/gstreamer-1.0-1.26.8-universal.pkg" -O /tmp/gst-1.0-1.26.8-universal.pkg
    - wget -q "https://gstreamer.freedesktop.org/data/pkg/osx/1.26.8/gstreamer-1.0-devel-1.26.8-universal.pkg" -O /tmp/gst-1.0-devel-1.26.8-universal.pkg
    - sudo installer -pkg /tmp/gst-1.0-1.26.8-universal.pkg -target /
    - sudo installer -pkg /tmp/gst-1.0-devel-1.26.8-universal.pkg -target /
    - export PKG_CONFIG_PATH=/Library/Frameworks/GStreamer.framework/Versions/1.0/lib/pkgconfig
    - export PATH=/Library/Frameworks/GStreamer.framework/Versions/1.0/bin:$PATH
    - export DYLD_LIBRARY_PATH=/Library/Frameworks/GStreamer.framework/Libraries:$DYLD_LIBRARY_PATH

    - cargo install --git https://github.com/indygreg/apple-platform-rs --branch main --bin rcodesign apple-codesign
    - cargo xtask sender build-macos-installer --sign --p12-file=./.secure_files/Certificates.p12 --p12-password-file=./.secure_files/p12_certs_password --api-key-file=./.secure_files/notary_key.json
  binary_artifacts:
    path: target/fcast-sender-*.*

sender_sdk_csharp_task:
  name crossCompileForDarwinCSharp
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:14.3.1
  buildSenderSdkDarwin_script:
    - brew install rustup-init protobuf
    - rustup-init -y
    - rustup target add aarch64-apple-darwin x86_64-apple-darwin
    - source $HOME/.cargo/env

    - cargo build --release --target aarch64-apple-darwin -p fcast-sender-sdk --no-default-features --features fcast,chromecast,uniffi,logging,discovery,_uniffi_csharp
    - cargo build --release --target x86_64-apple-darwin -p fcast-sender-sdk --no-default-features --features fcast,chromecast,uniffi,logging,discovery,_uniffi_csharp

  binary_artifacts:
    path: target/*-apple-darwin/release/libfcast_sender_sdk.dylib
