import {
    Icons,
    FText,
    ScrollView,
    Spinner,
    Button,
    Palette,
    ListView,
    Slider,
} from "../../../senders/ui-components/std-widgets.slint";
import { FCastPalette } from "../../../senders/ui-components/styling.slint";
import "../../../senders/ui-components/fonts/Outfit-Regular.ttf";
import {
    Bridge,
    GuiPlaybackState,
    AppState,
    UiPlayerVariant,
} from "globals.slint";
import { IdleView } from "views/idle.slint";
import { LoadingMediaView } from "views/loading-media.slint";
import { VideoPlayerView } from "views/video-player.slint";
import { ImageView } from "views/image.slint";
import { AudioPlayerView } from "views/audio-player.slint";
import { RaopView } from "views/raop.slint";
import { ToastOverlay } from "toast-overlay.slint";

export {
    Bridge,
    GuiPlaybackState,
    AppState,
    UiPlayerVariant,
}

export component MainWindow inherits Window {
    title: @tr("FCast Receiver");

    default-font-family: "Outfit";
    default-font-size: 15px;
    default-font-weight: 400;

    public function device-connected() {
        Bridge.connected_devices += 1;
    }

    FocusScope {
        capture-key-pressed(event) => Bridge.capture-key-pressed(event);
    }

    if Bridge.app-state == AppState.Playing && Bridge.player-variant == UiPlayerVariant.Video: VideoPlayerView { }

    if Bridge.app-state == AppState.Playing && Bridge.player-variant == UiPlayerVariant.Image: ImageView { }

    if Bridge.app-state == AppState.Playing && Bridge.player-variant == UiPlayerVariant.Audio: AudioPlayerView { }

    if Bridge.app-state == AppState.Playing && Bridge.player-variant == UiPlayerVariant.Raop: RaopView { }

    IdleView {
        opacity: Bridge.app-state == AppState.Idle ? 100% : 0%;
        visible: self.opacity > 0%;

        animate opacity {
            duration: 100ms;
        }
    }

    LoadingMediaView {
        opacity: Bridge.app-state == AppState.LoadingMedia ? 100% : 0%;
        visible: self.opacity > 0%;

        animate opacity {
            duration: 100ms;
        }
    }

    if Bridge.should-show-toast-overlay(): ToastOverlay { }
}
