
buildAndroidDockerContainer:
  stage: buildDockerContainers
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  tags:
    - fcast-instance-runner
  before_script:
    - cd receivers/android
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY/videostreaming/fcast/receiver-android-dev:latest .
    - docker push $CI_REGISTRY/videostreaming/fcast/receiver-android-dev:latest
  when: manual

buildReceiverAndroid:
  stage: receiverAndroid
  image: gitlab.futo.org:5050/videostreaming/fcast/receiver-android-dev:latest
  tags:
    - fcast-instance-runner
  variables:
    ANDROID_VERSION_NAME: "1"
    ANDROID_VERSION_CODE: "1"
  before_script:
    - cd receivers/android
  script:
    - echo "Building content..."
    - ./gradlew --stacktrace assembleRelease -PversionName=$ANDROID_VERSION_NAME -PversionCode=$ANDROID_VERSION_CODE
    - ./gradlew --stacktrace bundlePlaystoreRelease -PversionName=$ANDROID_VERSION_NAME -PversionCode=$ANDROID_VERSION_CODE
    - echo $ANDROID_VERSION_CODE > ./fcast-version.txt
    - mkdir -p /artifacts/$ANDROID_VERSION_CODE
    - cp -rf ./app/build/outputs/apk/defaultFlavor/release/app-defaultFlavor-release.apk /artifacts/$ANDROID_VERSION_CODE/fcast-release.apk
    - cp -rf ./app/build/outputs/bundle/playstoreRelease/app-playstore-release.aab /artifacts/$ANDROID_VERSION_CODE/fcast-playstore-release.aab
    - cp -rf ./fcast-version.txt /artifacts/fcast-version.txt

    # Artifact uploads require artifacts to be in project directory
    - mkdir -p ./$ANDROID_VERSION_CODE
    - mv /artifacts/fcast-version.txt ./$ANDROID_VERSION_CODE/fcast-version.txt
    - mv ./app/build/outputs/apk/defaultFlavor/release/app-defaultFlavor-release.apk ./$ANDROID_VERSION_CODE/fcast-release.apk
    - mv ./app/build/outputs/bundle/playstoreRelease/app-playstore-release.aab ./$ANDROID_VERSION_CODE/fcast-playstore-release.aab
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: "30 days"
    paths:
      - receivers/android/$ANDROID_VERSION_CODE/fcast-version.txt
      - receivers/android/$ANDROID_VERSION_CODE/fcast-release.apk
      - receivers/android/$ANDROID_VERSION_CODE/fcast-playstore-release.aab
  when: manual
