build_sender_android:
  stage: senders
  tags:
    - fcast-autoscaler
  variables:
    ANDROID_VERSION_NAME: "1"
    ANDROID_VERSION_CODE: "1"
  script:
    - sudo dnf install -y gcc-c++ gcc cmake pkgconfig automake autoconf libtool java-21-openjdk-devel
      xz curl ninja-build clang-devel zip git-lfs
    - git lfs install
    - rm -rf $HOME/.rustup
    - rustup self update
    - rustup default stable
    - rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android
      x86_64-unknown-linux-gnu
    - source $HOME/.cargo/env
    - cargo install --locked cargo-ndk --git https://github.com/bbqsrc/cargo-ndk --rev 9672f442e3524139f3369720cd8d83c8f29b7303

    - git clone --depth=1 "https://gitlab.futo.org/videostreaming/fcast-android-sender-build-deps.git" deps
    - cd deps
    - git lfs pull
    - cd ..

    - unzip deps/commandlinetools-linux-11076708_latest.zip -d thirdparty/
    - export ANDROID_HOME="$PWD/thirdparty/Android/Sdk"

    - yes | ./thirdparty/cmdline-tools/bin/sdkmanager --sdk_root="$ANDROID_HOME" --licenses || true
    - ./thirdparty/cmdline-tools/bin/sdkmanager --sdk_root="$ANDROID_HOME" --install "platforms;android-35"
    - ./thirdparty/cmdline-tools/bin/sdkmanager --sdk_root="$ANDROID_HOME" --install "build-tools;35.0.0"

    - mkdir -p thirdparty/gstreamer-1.0-android-universal-1.28.1
    - tar -xf deps/gstreamer-1.0-android-universal-1.28.1.tar.xz -C thirdparty/gstreamer-1.0-android-universal-1.28.1
    - export GST_PATH="$PWD/thirdparty/gstreamer-1.0-android-universal-1.28.1"

    - unzip deps/android-ndk-r25c-linux.zip -d thirdparty/
    - export ANDROID_NDK_ROOT="$PWD/thirdparty/android-ndk-r25c"

    - cargo xtask sender android
      --android-home-override="$ANDROID_HOME" --android-ndk-root-override="$ANDROID_NDK_ROOT" --gstreamer-root-override="$GST_PATH"
      build-lib-gst

    - cargo xtask sender android
      --android-home-override="$ANDROID_HOME" --android-ndk-root-override="$ANDROID_NDK_ROOT" --gstreamer-root-override="$GST_PATH"
      build --release

    - cd senders/android
    - ./gradlew assembleRelease -PversionName=$ANDROID_VERSION_NAME -PversionCode=$ANDROID_VERSION_CODE

    - mkdir -p "./$ANDROID_VERSION_CODE"
    - mv ./app/build/outputs/apk/release/app-release-unsigned.apk "./$ANDROID_VERSION_CODE/fcast-sender-release.apk"
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: "30 days"
    paths:
      - senders/android/$ANDROID_VERSION_CODE/fcast-sender-release.apk
  when: manual
