build_android_sender_docker_container:
  stage: buildDockerContainers
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  tags:
    - fcast-instance-runner
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY/videostreaming/fcast/android-sender-dev:latest senders/android/
    - docker push $CI_REGISTRY/videostreaming/fcast/android-sender-dev:latest
  when: manual


build_sender_android:
  stage: senders
  image: gitlab.futo.org:5050/videostreaming/fcast/android-sender-dev:latest
  tags:
    - fcast-instance-runner
  script:
    - rustup default stable
      && rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android x86_64-unknown-linux-gnu
      && {
        cargo install --locked cargo-ndk --git https://github.com/bbqsrc/cargo-ndk --rev 9672f442e3524139f3369720cd8d83c8f29b7303 &
        cargo xtask --help &
      } &

    - git clone --depth=1 "https://gitlab.futo.org/videostreaming/fcast-android-sender-build-deps.git" deps
    - cd deps
    - git lfs pull
    - cd ..

    - mkdir thirdparty/
    - unzip -qq deps/android-ndk-r25c-linux.zip -d thirdparty/ &

    - mkdir -p thirdparty/gstreamer-1.0-android-universal-1.28.3
    - tar -xf deps/gstreamer-1.0-android-universal-1.28.3.tar.xz -C thirdparty/gstreamer-1.0-android-universal-1.28.3 &

    - unzip -qq deps/commandlinetools-linux-11076708_latest.zip -d thirdparty/
    - export ANDROID_HOME="$PWD/thirdparty/Android/Sdk"
    - yes | ./thirdparty/cmdline-tools/bin/sdkmanager --sdk_root="$ANDROID_HOME" --licenses > /dev/null 2>&1 || true
    - ./thirdparty/cmdline-tools/bin/sdkmanager --sdk_root="$ANDROID_HOME" --install "platforms;android-35"
    - ./thirdparty/cmdline-tools/bin/sdkmanager --sdk_root="$ANDROID_HOME" --install "build-tools;35.0.0"

    - wait

    - export GST_PATH="$PWD/thirdparty/gstreamer-1.0-android-universal-1.28.3"
    - export ANDROID_NDK_ROOT="$PWD/thirdparty/android-ndk-r25c"

    - cargo xtask sender android
      --android-home-override="$ANDROID_HOME" --android-ndk-root-override="$ANDROID_NDK_ROOT" --gstreamer-root-override="$GST_PATH"
      build-lib-gst

    - cargo xtask sender android
      --android-home-override="$ANDROID_HOME" --android-ndk-root-override="$ANDROID_NDK_ROOT" --gstreamer-root-override="$GST_PATH"
      build --release

    - cd senders/android
    - ./gradlew assembleRelease
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: "3 days"
    paths:
      - senders/android/app/build/outputs/apk/release/*.apk
  when: manual
