import {
    Button,
    ComboBox,
    Palette,
    Spinner,
    Switch,
    TextEdit,
    Slider,
    LineEdit,
    Palette,
    FText,
    ListView,
} from "../../ui-components/std-widgets.slint";
import "../../ui-components/fonts/Outfit-Regular.ttf";

export component FCastWidgetsGallery inherits Window {
    default-font-family: "Outfit";
    default-font-size: 15px;
    default-font-weight: 400;

    background: Palette.background;

    HorizontalLayout {
        alignment: center;
        VerticalLayout {
            Image {
                source: @image-url("fcast-icon.png");
                width: 64px;
            }

            alignment: center;
            spacing: 10px;
            Button {
                text: "Continue";
            }

            Button {
                enabled: false;
                text: "Continue";
            }

            Button {
                width: 42px;
                colorize-icon: true;
                icon: @image-url("./play.svg");
            }
        }
    }
}
