
buildMacOs:
  stage: buildAndDeployElectron
  tags:
    - m1-macos
  before_script:
    - cd receivers/electron
    - echo testing envrionment variable access $TESTVAR
    - security unlock-keychain -p "$KEYCHAIN_CODESIGN_PASSWORD" "$HOME/Library/Keychains/codesign.keychain-db"
  script:
    - npm install
    - npm run build
    - npm run make -- --platform="darwin" --arch="arm64"
  when: manual

deploy:
  stage: buildAndDeployElectron
  # before_script:
  #   - cd receivers/electron
  script:
    - sh deploy.sh
  when: manual