
buildMacOs:
  stage: buildAndDeployElectron
  tags:
    - m1-macos
  before_script:
    - cd receivers/electron
  script:
    - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - brew install npm
    - npm install
    - npm run make --arch arm64
  when: manual

deploy:
  stage: buildAndDeployElectron
  # before_script:
  #   - cd receivers/electron
  script:
    - sh deploy.sh
  when: manual