
buildMac:
  stage: buildAndDeployElectron
  tags:
    - m1-macos
  before_script:
    - cd receivers/electron
  script:
    - npm install
    - npm run build
    - npm run make -- --platform="darwin" --arch="arm64"
    - npm run make -- --platform="darwin" --arch="x64"
  when: manual

buildLinux:
  stage: buildAndDeployElectron
  tags:
    - fcast
  before_script:
    - cd receivers/electron
  script:
    - npm install
    - npm run build
    - npm run make -- --platform="darwin" --arch="arm64"
  when: manual

deploy:
  stage: buildAndDeployElectron
  # before_script:
  #   - cd receivers/electron
  script:
    - sh deploy.sh
  when: manual