buildSenderSDKDockerContainer:
  stage: buildDockerContainers
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  tags:
    - fcast-instance-runner
  before_script:
    - cd sdk/sender
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY/videostreaming/fcast/sender-sdk-dev:latest .
    - docker push $CI_REGISTRY/videostreaming/fcast/sender-sdk-dev:latest
  when: manual

buildAndroid:
  stage: buildSenderSDK
  image: gitlab.futo.org:5050/videostreaming/fcast/sender-sdk-dev:latest
  script:
    - cargo xtask kotlin build-android-library --release --src-dir sdk/sender/out
    - cp -rf sdk/sender/out/* /artifacts/
  tags:
    - fcast-instance-runner
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: "3 days"
    paths:
      - sdk/sender/out/*
  when: manual

buildIos:
  stage: buildSenderSDK
  image: ghcr.io/cirruslabs/macos-ventura-xcode@sha256:3380f24929d01a7ac48a554dd242340739387822cf1cb0d96be839ef91b89daf
  tags:
    - tart-installed
  before_script:
    - brew install rustup protobuf
    - rustup default stable
    - rustup target add aarch64-apple-ios-sim aarch64-apple-ios
    - source $HOME/.cargo/env
  script:
    - cargo xtask generate-ios
    - cp -rf ios-bindings/* /artifacts/
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: "3 days"
    paths:
      - ios-bindings/*
  when: manual

cargoHackSenderSDK:
  stage: testSDK
  image: gitlab.futo.org:5050/videostreaming/fcast/sender-sdk-dev:latest
  script:
    - cargo hack check -p fcast-sender-sdk --each-feature
  tags:
    - fcast-instance-runner
  when: manual

cargoTestSenderSDK:
  stage: testSDK
  image: gitlab.futo.org:5050/videostreaming/fcast/sender-sdk-dev:latest
  script:
    - cargo test --verbose
  tags:
    - fcast-instance-runner
  when: manual
