# https://www.docker.com/blog/cross-compiling-rust-code-for-multiple-architectures/
# docker build --no-cache -t fcast/sender-sdk-dev-cross-x86_64-unknown-linux-gnu:latest -f Dockerfile.cross-x86_64-unknown-linux-gnu .
# docker run --rm -it -w /app --entrypoint='bash' --network host -v .:/app fcast/sender-sdk-dev-cross-x86_64-unknown-linux-gnu:latest

FROM rust:latest

RUN apt update && apt upgrade -y
RUN apt install -y protobuf-compiler

RUN rustup target add x86_64-unknown-linux-gnu
