# https://www.docker.com/blog/cross-compiling-rust-code-for-multiple-architectures/
# docker build --no-cache -t fcast/sender-sdk-dev-cross-aarch64-unknown-linux-gnu:latest -f Dockerfile.cross-aarch64-unknown-linux-gnu .
# docker run --rm -it -w /app --entrypoint='bash' --network host -v .:/app fcast/sender-sdk-dev-cross-aarch64-unknown-linux-gnu:latest

FROM rust:latest

RUN apt update && apt upgrade -y
RUN apt install -y g++-aarch64-linux-gnu libc6-dev-arm64-cross protobuf-compiler

RUN rustup target add aarch64-unknown-linux-gnu
RUN rustup toolchain install stable-aarch64-unknown-linux-gnu --force-non-host

ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
ENV CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
ENV CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++
