import { VerticalBox } from "std-widgets.slint";
import { Button, Spinner, FText, ScrollView, Icons, Palette, NoReceiverFound, RoundBackButton, Spacer, ListView, SecondaryText, LicenseAndCopyrightNotice } from "../../ui-components/std-widgets.slint";
import { FCastPalette } from "../../ui-components/styling.slint";
import { Utils, VideoResolutionPicker, FrameratePicker } from "../../../sdk/mirroring_core/ui/common.slint";
import "../../ui-components/fonts/Outfit-Regular.ttf";

enum AppState {
    Disconnected,
    Connecting,
    SelectingSettings,
    WaitingForMedia,
    Casting,
}

export global Bridge {
    in property <[string]> devices: [
        // "Device 1", "Device 2",
    ];
    in-out property <AppState> app-state: AppState.Disconnected;
    // in-out property <AppState> app-state: AppState.SelectingSettings;
    in-out property <string> current-device-name;
    in-out property <bool> is-showing-settings: false;

    callback connect-receiver(string);
    callback start-casting(scale-width: int, scale-height: int, max-framerate: int);
    callback stop-casting();
    callback scan-qr();

    public function change-state(to: AppState) {
        if to == AppState.Disconnected {
            current-device-name = "";
        }

        Bridge.app-state = to;
    }
}

component TopBar inherits Rectangle {
    background: FCastPalette.neutral-1100;

    HorizontalLayout {
        padding: 12px;

        if Bridge.app-state == AppState.SelectingSettings: RoundBackButton {
            clicked => Bridge.stop-casting();
        }

        Spacer { }

        Rectangle {
            width: 30px;
            height: 30px;

            TouchArea {
                clicked => {
                    Bridge.is-showing-settings = !Bridge.is-showing-settings;
                }
            }

            Image {
                source: Bridge.is-showing-settings ? Icons.close : Icons.bars;
                colorize: Palette.foreground;
                width: Bridge.is-showing-settings ? 20px : parent.width;
                height: Bridge.is-showing-settings ? 20px : parent.height;
            }
        }
    }
}

component DeviceListItem {
    in property <string> dev-name;
    in property <bool> fcast;

    accessible-role: list-item;

    states [
        hover when i-touch-area.has-hover: {
            i-background.background: FCastPalette.brand-600.transparentize(92%);
            i-background.border-width: 1px;
            i-background.border-color: #1478DC33;
        }
    ]

    i-touch-area := TouchArea {
        clicked => {
            Bridge.connect-receiver(dev-name);
            Bridge.current-device-name = dev-name;
        }
    }

    i-background := Rectangle {
        background: #13151B;
        border-radius: 8px;

        VerticalLayout {
            HorizontalLayout {
                padding: 5px;
                spacing: 5px;

                Image {
                    width: 36px;
                    height: 36px;
                    source: Icons.tv;
                    vertical-alignment: center;
                }

                FText {
                    text: dev-name;
                    font-size: 16px;
                    vertical-alignment: center;
                    overflow: elide;
                }
            }
        }
    }
}

component ConnectView inherits Rectangle {
    background: FCastPalette.neutral-1200;

    VerticalBox {
        if Bridge.devices.length > 0: FText {
            horizontal-alignment: center;
            font-size: 16px;
            font-weight: 600;
            text: "Discovered receivers";
        }

        if Bridge.devices.length > 0: FText {
            text: "Scanning local network (mDNS) for FCast-enabled devices...";
            wrap: word-wrap;
            font-size: 12px;
            horizontal-alignment: center;
            color: grey;
        }

        if Bridge.devices.length > 0: ScrollView {
            VerticalLayout {
                padding-top: 20px;
                spacing: 8px;
                for device in Bridge.devices: DeviceListItem {
                    dev-name: device;
                }
            }
        }

        if Bridge.devices.length == 0: NoReceiverFound { }

        Button {
            text: "Scan QR";
            clicked => {
                Bridge.scan-qr();
                Bridge.current-device-name = "scanned device";
            }
        }
    }
}

component ConnectingView inherits Rectangle {
    VerticalBox {
        Spinner {
            indeterminate: true;
        }

        FText {
            font-size: 12pt;
            vertical-alignment: center;
            text: "Connecting";
        }

        Button {
            text: "Cancel";
            clicked => Bridge.stop-casting();
        }
    }
}

component SelectingSettingsView inherits Rectangle {
    property <int> video-resolution-idx: 2;
    property <int> video-framerate-idx: 2;

    VerticalLayout {
        VerticalBox {
            alignment: center;

            FText {
                font-size: 12pt;
                vertical-alignment: center;
                text: "Max resolution";
            }

            VideoResolutionPicker {
                current-index <=> video-resolution-idx;
            }

            FText {
                font-size: 12pt;
                vertical-alignment: center;
                text: "Max framerate";
            }

            FrameratePicker {
                current-index <=> video-framerate-idx;
            }

            Button {
                text: "Start";
                clicked => {
                    let scale = Utils.str-to-scale(video-resolution-idx);
                    Bridge.start-casting(scale.width, scale.height, Utils.video-framerates[video-framerate-idx].to-float());
                }
            }
        }
    }
}

component WaitingForMediaView inherits Rectangle {
    VerticalBox {
        FText {
            horizontal-alignment: center;
            text: "Waiting for media";
        }
    }
}

component CastingView inherits Rectangle {
    HorizontalLayout {
        alignment: center;

        VerticalBox {
            alignment: center;

            FText {
                horizontal-alignment: center;
                text: "Mirroring to " + Bridge.current-device-name;
                wrap: word-wrap;
            }

            Button {
                text: "Stop";
                clicked => Bridge.stop-casting();
            }
        }
    }
}

component SettingsView inherits Rectangle {
    background: FCastPalette.background-color-primary;

    VerticalLayout {
        padding: 10px;

        spacing: 10px;

        Spacer {}

        LicenseAndCopyrightNotice { }
    }
}

export component MainWindow inherits Window {
    title: "FCast Sender";
    icon: @image-url("../../extra/fcast.png");

    default-font-family: "Outfit";
    default-font-size: 15px;
    default-font-weight: 400;

    background: FCastPalette.background-color-primary;

    VerticalLayout {
        TopBar { }

        if !Bridge.is-showing-settings: Rectangle {
            if Bridge.app-state == AppState.Disconnected: ConnectView { }

            if Bridge.app-state == AppState.Connecting: ConnectingView { }

            if Bridge.app-state == AppState.SelectingSettings: SelectingSettingsView { }

            if Bridge.app-state == AppState.WaitingForMedia: WaitingForMediaView { }

            if Bridge.app-state == AppState.Casting: CastingView { }
        }

        if Bridge.is-showing-settings: SettingsView { }
    }
}
