import { Icons, FText } from "../../../../ui-components/std-widgets.slint";
import { Assets } from "../globals.slint";

export component LoadingMediaView inherits Rectangle {
    Image {
        source: Assets.background-dark;
        width: 100%;
        height: 100%;
    }

    VerticalLayout {
        alignment: center;

        FText {
            text: @tr("Loading media...");
            horizontal-alignment: center;
        }
    }
}
