import {
    Icons,
    FText,
    ScrollView,
    Button,
    ListView,
} from "../../../../senders/ui-components/std-widgets.slint";
import {
    Bridge,
    UiMediaTrack,
    GuiPlaybackState,
    UiMediaTrackType,
    UiMode,
} from "../globals.slint";
import {
    PositionScrubber,
    ProgressLabels,
    MasterButton,
    ScrubbyMcScrub,
    VolumePreview,
    SubtitleView,
} from "../common.slint";
import {
    FCastPalette,
} from "../../../../senders/ui-components/styling.slint";

component SecondaryButton inherits Button {
    icon-size: 18px;
    width: 45px;
    height: 45px;
    background-default-color: @linear-gradient(133.14deg, rgba(204, 204, 204, 0.1) 6.7%, rgba(122, 122, 122, 0.1) 92.77%);
    colorize-icon: true;
}

component PlaybackSettingsMenuItem inherits Rectangle {
    in property <string> label;
    in property <image> icon;

    callback clicked;

    border-radius: 6px;

    states [
        hover when i-ta.has-hover: {
            text.color: FCastPalette.foreground;
            arrow-icon.colorize: FCastPalette.foreground;
            background: FCastPalette.brand-600;
        }
    ]

    i-ta := TouchArea {
        clicked => root.clicked();
        mouse-cursor: pointer;
    }

    HorizontalLayout {
        padding: 8px;
        padding-top: 14px;
        padding-bottom: 14px;
        spacing: 8px;

        VerticalLayout {
            alignment: center;

            Image {
                width: 16px;
                height: 16px;
                source: icon;
            }
        }

        text := FText {
            text: label;
            color: FCastPalette.neutral-500;
        }

        Rectangle { }

        VerticalLayout {
            alignment: center;

            arrow-icon := Image {
                width: 4.67px;
                height: 8px;
                source: Icons.arrow-right;
            }
        }
    }
}

component SettingItem inherits Rectangle {
    in property <string> value;
    in property <bool> selected;

    callback clicked;

    border-radius: 6px;

    states [
        selected when selected: {
            background: @linear-gradient(90.92deg, #2D7AF8 0.79%, #0757D9 104.49%);
            icon.source: Icons.check-tick;
        }
        hover when ta.has-hover: {
            background: @linear-gradient(90.92deg, #2D7AF850 0.79%, #0757D950 104.49%);
        }
    ]

    ta := TouchArea {
        mouse-cursor: pointer;

        clicked => clicked();
    }

    HorizontalLayout {
        padding: 10px;
        padding-left: 12px;
        padding-right: 12px;

        FText {
            text: value;
        }

        Rectangle { }

        VerticalLayout {
            alignment: center;

            icon := Image {
                source: Icons.arrow-right;
            }
        }
    }
}

component PlaybackSettingHeader inherits HorizontalLayout {
    in property <string> title;

    callback navigate-previous;

    spacing: 15px;

    Button {
        icon: Icons.arrow-right;
        icon-size: 8px;
        width: 30px;
        height: 30px;
        transform-rotation: 180deg;
        colorize-icon: true;

        clicked => navigate-previous();
    }

    FText {
        text: title;
        font-weight: 500;
        font-size: 18px;
        vertical-alignment: center;
    }
}

component SettingsTrackList inherits VerticalLayout {
    in property <[UiMediaTrack]> tracks;
    in property <int> selected-id;
    in property <bool> can-be-disabled: false;

    callback clicked(id: int);

    if can-be-disabled: SettingItem {
        value: "Off";
        selected: selected-id == -1;

        clicked => clicked(-1);
    }

    Rectangle {
        height: 1px;
        background: #FFFFFF0A;
    }

    for track[id] in tracks: VerticalLayout {
        SettingItem {
            value: track.name;
            selected: selected-id == id;

            clicked => clicked(id);
        }

        Rectangle {
            height: 1px;
            background: #FFFFFF0A;
        }
    }
}

component ButtonControls inherits Rectangle {
    callback show-settings();

    HorizontalLayout {
        alignment: space-between;

        Rectangle {
            width: right-side-ctrls.preferred-width;
        }

        Rectangle {
            MasterButton {
                height: 50px;
                width: 50px;
            }
        }

        right-side-ctrls := HorizontalLayout {
            alignment: end;
            spacing: 15px;

            settings-btn := SecondaryButton {
                icon: Icons.settings;
                clicked => show-settings();
            }
        }
    }
}

enum SettingsPage {
    Start,
    Video,
    Audio,
    Subtitle,
    Rate,
}

component PlaybackControls inherits Rectangle {
    out property <MouseCursor> suggested-cursor: default;

    property <bool> is-changing-volume: false;
    property <float> background-height: 100%;
    property <float> elems-opacity: 0%;
    property <bool> show-elems: true;
    property <bool> show-settings: false;
    property <SettingsPage> current-settings-page: SettingsPage.Start;

    animate elems-opacity, background-height {
        duration: 200ms;
        easing: ease-out-expo;
    }

    VerticalLayout {
        Rectangle {
            background: @linear-gradient(0deg, rgba(0, 0, 0, 0.0), rgba(0, 0, 0, 0.8) 100%);
        }

        Rectangle {
            height: parent.height * background-height;
        }

        Rectangle {
            background: @linear-gradient(0deg, rgba(0, 0, 0, 1.0) 0%, rgba(0, 0, 0, 0.0) 100%);
        }
    }

    public function show() {
        show-elems = true;
        background-height = 20%;
        elems-opacity = 100%;
        tim.running = true;
        tim.restart();
        suggested-cursor = MouseCursor.default;
    }

    public function close() {
        background-height = 100%;
        elems-opacity = 0%;
        tim.running = false;
        suggested-cursor = MouseCursor.none;
    }

    // TODO: handle the case when focus leaves window
    ta := TouchArea {
        mouse-cursor: suggested-cursor;

        clicked => {
            show-settings = false;
        }

        pointer-event(pe) => {
            if (pe.kind == PointerEventKind.move) {
                parent.show();
            }
        }
    }

    main-vlayout := VerticalLayout {
        padding: 58px;
        padding-top: 20px;
        padding-bottom: 20px;
        spacing: 5px;

        if Bridge.ui-mode == UiMode.Full: HorizontalLayout {
            opacity: elems-opacity;
            visible: show-elems;

            Rectangle { }

            SecondaryButton {
                opacity: elems-opacity;
                icon: Bridge.is-fullscreen ? Icons.minimize : Icons.maximize;

                clicked => Bridge.toggle-fullscreen();
            }
        }

        Rectangle { }

        if Bridge.render-subtitles && Bridge.subtitles.length > 0: SubtitleView { }

        ctrl-layout := Rectangle {
            height: self.preferred-height * elems-opacity;

            VerticalLayout {
                HorizontalLayout {
                    opacity: elems-opacity;
                    visible: show-elems;
                    padding: 10px;
                    padding-bottom: 15px;

                    FText {
                        text: Bridge.media-title;
                        width: 50%;
                        wrap: word-wrap;
                        overflow: elide;
                        font-size: 24px;
                        max-height: 5px;
                        font-weight: 500;
                        color: FCastPalette.neutral-100;
                    }

                    Rectangle { /* Spacer */ }

                    if Bridge.is-live: VerticalLayout {
                        opacity: elems-opacity;

                        Rectangle { }

                        Rectangle {
                            background: #FB2C2C;
                            border-radius: 3.3px;
                            width: i-hl.preferred-width;

                            i-hl := HorizontalLayout {
                                padding: 12px;
                                padding-top: 6px;
                                padding-bottom: self.padding-top;
                                spacing: 6px;

                                VerticalLayout {
                                    alignment: center;

                                    Rectangle {
                                        width: 8px;
                                        height: 8px;
                                        border-radius: 5px;
                                        background: FCastPalette.foreground;
                                    }
                                }

                                FText {
                                    text: "LIVE";
                                    font-weight: 500;
                                    vertical-alignment: center;
                                }
                            }
                        }
                    }
                }

                ScrubbyMcScrub {
                    opacity: elems-opacity;
                    visible: show-elems;
                    height: show-elems ? self.preferred-height : 0px;
                }

                if Bridge.ui-mode == UiMode.Full: Rectangle {
                    height: 5px;
                }

                if Bridge.ui-mode == UiMode.Full: ButtonControls {
                    opacity: elems-opacity;
                    visible: show-elems;

                    show-settings => {
                        show-settings = true;
                    }
                }
            }
        }
    }

    if show-settings: Rectangle {
        background: @linear-gradient(180deg, #101010 0%, #0F0F10 100%);
        border-color: @radial-gradient(circle, rgba(255, 255, 255, 0.04) 0%, rgba(102, 102, 102, 0.04) 100%);
        border-width: 1px;
        border-radius: 6px;
        width: settings-inner.preferred-width;
        height: current-settings-page == SettingsPage.Start
        ? settings-start.preferred-height
        : current-settings-page == SettingsPage.Video
        ? settings-video.preferred-height
        : current-settings-page == SettingsPage.Audio
        ? settings-audio.preferred-height
        : current-settings-page == SettingsPage.Subtitle
        ? settings-subtitle.preferred-height
        : current-settings-page == SettingsPage.Rate
        ? settings-rate.preferred-height
        : settings-inner.preferred-height;
        x: ctrl-layout.x + ctrl-layout.width - self.width;
        y: ctrl-layout.y + 105px - self.height;

        TouchArea {}

        settings-inner := Rectangle {
            settings-start := VerticalLayout {
                padding: 15px;
                padding-top: 18px;
                height: current-settings-page == SettingsPage.Start ? self.preferred-height : 0px;
                visible: current-settings-page == SettingsPage.Start;

                FText {
                    text: "Playback settings";
                    font-weight: 500;
                    font-size: 18px;
                }

                VerticalLayout {
                    padding-top: 10px;
                    spacing: 5px;

                    if Bridge.video-tracks.length > 0: PlaybackSettingsMenuItem {
                        label: "Video";
                        icon: Icons.settings-video;

                        clicked => {
                            current-settings-page = SettingsPage.Video;
                        }
                    }

                    if Bridge.audio-tracks.length > 0: PlaybackSettingsMenuItem {
                        label: "Audio";
                        icon: Icons.details-audio;

                        clicked => {
                            current-settings-page = SettingsPage.Audio;
                        }
                    }

                    if Bridge.subtitle-tracks.length > 0: PlaybackSettingsMenuItem {
                        label: "Subtitles";
                        icon: Icons.subtitles;

                        clicked => {
                            current-settings-page = SettingsPage.Subtitle;
                        }
                    }

                    PlaybackSettingsMenuItem {
                        label: "Playback Speed";
                        icon: Icons.playback-rate;

                        clicked => {
                            current-settings-page = SettingsPage.Rate;
                        }
                    }
                }
            }

            settings-video := VerticalLayout {
                padding: 15px;
                padding-top: 18px;
                height: current-settings-page == SettingsPage.Video ? self.preferred-height : 0px;
                visible: current-settings-page == SettingsPage.Video;

                PlaybackSettingHeader {
                    title: "Video track";

                    navigate-previous => {
                        current-settings-page = SettingsPage.Start;
                    }
                }

                VerticalLayout {
                    padding-top: 10px;
                    spacing: 5px;

                    // TODO: scroll view if needed
                    SettingsTrackList {
                        tracks: Bridge.video-tracks;
                        selected-id: Bridge.current-video-track;
                        clicked(id) => Bridge.select-track(id, UiMediaTrackType.Video);
                    }
                }
            }

            settings-audio := VerticalLayout {
                padding: 15px;
                padding-top: 18px;
                height: current-settings-page == SettingsPage.Audio ? self.preferred-height : 0px;
                visible: current-settings-page == SettingsPage.Audio;

                PlaybackSettingHeader {
                    title: "Audio track";

                    navigate-previous => {
                        current-settings-page = SettingsPage.Start;
                    }
                }

                VerticalLayout {
                    padding-top: 10px;
                    spacing: 5px;

                    // TODO: scroll view if needed
                    SettingsTrackList {
                        tracks: Bridge.audio-tracks;
                        selected-id: Bridge.current-audio-track;
                        clicked(id) => Bridge.select-track(id, UiMediaTrackType.Audio);
                    }
                }
            }

            settings-subtitle := VerticalLayout {
                padding: 15px;
                padding-top: 18px;
                height: current-settings-page == SettingsPage.Subtitle ? self.preferred-height : 0px;
                visible: current-settings-page == SettingsPage.Subtitle;

                PlaybackSettingHeader {
                    title: "Subtitle track";

                    navigate-previous => {
                        current-settings-page = SettingsPage.Start;
                    }
                }

                VerticalLayout {
                    padding-top: 10px;
                    spacing: 5px;

                    // TODO: scroll view if needed
                    SettingsTrackList {
                        alignment: start;
                        tracks: Bridge.subtitle-tracks;
                        selected-id: Bridge.current-subtitle-track;
                        can-be-disabled: true;
                        clicked(id) => {
                            // HACK: needed until https://gitlab.freedesktop.org/gstreamer/gstreamer/-/work_items/4744 is fixed
                            if id != -1 {
                                Bridge.render-subtitles = true;
                                Bridge.select-track(id, UiMediaTrackType.Subtitle);
                            } else {
                                Bridge.render-subtitles = false;
                                Bridge.current-subtitle-track = -1;
                            }
                        }
                    }
                }
            }

            settings-rate := VerticalLayout {
                padding: 15px;
                padding-top: 18px;
                height: current-settings-page == SettingsPage.Rate ? self.preferred-height : 0px;
                visible: current-settings-page == SettingsPage.Rate;

                PlaybackSettingHeader {
                    title: "Playback speed";

                    navigate-previous => {
                        current-settings-page = SettingsPage.Start;
                    }
                }

                VerticalLayout {
                    padding-top: 10px;
                    spacing: 5px;

                    property <[float]> rates: [0.25, 0.5, 0.75, 1.0, 1.25, 1.50, 1.75, 2.0];

                    ListView {
                        height: 200px;

                        for rate in rates: VerticalLayout {
                            SettingItem {
                                value: rate;
                                selected: Bridge.playback-rate == rate;

                                clicked => {
                                    Bridge.change-playback-rate(rate);
                                    Bridge.playback-rate = rate;
                                }
                            }

                            Rectangle {
                                height: 1px;
                                background: #FFFFFF0A;
                            }
                        }
                    }
                }
            }
        }
    }

    tim := Timer {
        interval: 2s;
        running: true;
        triggered => {
            if ta.has-hover && !show-settings {
                parent.close();
                Bridge.hide-cursor-hack();
            }
        }
    }
}

export component VideoPlayerView inherits Rectangle {
    width: 100%;
    height: 100%;
    background: transparent;

    pure function scale() -> length {
        Math.min(root.height / Bridge.video-frame-height, root.width / Bridge.video-frame-width)
    }

    pure function frame-x() -> length {
        root.width / 2 - Bridge.video-frame-width * scale() / 2
    }

    pure function frame-y() -> length {
        root.height / 2 - Bridge.video-frame-height * scale() / 2
    }

    for overlay in Bridge.overlays: Image {
        x: frame-x() + (overlay.x * scale() / 1px);
        y: frame-y() + (overlay.y * scale() / 1px);
        width: overlay.img.width * 1px * scale() / 1px;
        height: overlay.img.height * 1px * scale() / 1px;
        source: overlay.img;
    }

    VolumePreview {
        width: 100%;
        height: 100%;
    }

    TouchArea {
        width: 100%;
        height: 100%;
        visible: Bridge.is-playing();
        mouse-cursor: self.visible && !playback-control.visible ? none : default;

        FocusScope {
            capture-key-pressed(event) => Bridge.capture-key-pressed(event);
        }

        playback-control := PlaybackControls {
            width: 100%;
            height: 100%;
        }
    }
}
