import {
    VerticalBox,
    HorizontalBox,
    Button,
    ComboBox,
    Palette,
    Spinner,
    Switch,
    ListView,
} from "std-widgets.slint";

export enum AppState {
    Disconnected,
    Connecting,
    SelectingSource,
    UnsupportedReceiver,
    StartingCast,
    Casting,
}

export struct VideoSourceModel {
    name: string,
    uid: int,
}

export struct AudioSourceModel {
    name: string,
    uid: int,
}

export global Bridge {
    in property <[string]> devices: [];
    in-out property <AppState> app-state: Disconnected;
    in-out property <string> device-name: "";
    in-out property <int> selected-video-src: -1;
    in-out property <int> selected-audio-src: -1;
    in-out property <[[VideoSourceModel]]> video-sources: [];
    in-out property <[[AudioSourceModel]]> audio-sources: [];
    in property <bool> is-audio-supported: false;

    public function change-state(to: AppState) {
        if to == AppState.Disconnected {
            selected-video-src = -1;
            selected-audio-src = -1;
            device-name = "";
            video-sources = [];
            audio-sources = [];
        }
        app-state = to;
    }

    callback connect-to-device(string);
    callback start-cast(video_uid: int, audio_uid: int);
    callback stop-cast();
    callback reload-video-sources();
    callback reload-audio-sources();
}

component ConnectView inherits Rectangle {
    VerticalBox {
        Text {
            horizontal-alignment: center;
            font-weight: 600;
            text: "Connect to your receiver";
        }

        ListView {
            for device in Bridge.devices: Rectangle {
                background: ta.has-hover ? whitesmoke : #00000000;
                ta := TouchArea {
                    mouse-cursor: self.has-hover ? pointer : default;
                    clicked => {
                        // Bridge.state = State.Connecting;
                        self.mouse-cursor = MouseCursor.default;
                        Bridge.connect-to-device(device);
                        // Bridge.connected-device = device;
                    }
                }

                HorizontalBox {
                    Text {
                        text: device;
                    }
                }
            }
        }
    }
}

component ConnectingView inherits Rectangle {
    width: vb.preferred-width;
    height: vb.preferred-height;

    vb := VerticalBox {
        Spinner {
            indeterminate: true;
        }

        Text {
            text: "Connecting to " + Bridge.device-name;
            horizontal-alignment: center;
            font-weight: 600;
        }
    }
}

component UnsupportedReceiverView inherits Rectangle {
    width: vb.preferred-width;
    height: vb.preferred-height;

    vb := VerticalBox {
        Text {
            text: Bridge.device-name + " is unsupported";
            horizontal-alignment: center;
            font-weight: 600;
        }

        Button {
            text: "Ok";
            clicked => Bridge.change-state(AppState.Disconnected);
        }
    }
}

component SelectSourceView inherits Rectangle {
    VerticalBox {
        alignment: center;

        HorizontalBox {
            alignment: space-between;
            Text {
                horizontal-alignment: center;
                text: "Video";
                font-weight: 600;
            }

            Button {
                text: "Reload";
                clicked => {
                    Bridge.video-sources = [];
                    Bridge.reload-video-sources();
                }
            }
        }

        // TODO: ScrollView

        VerticalLayout {
            for row in Bridge.video-sources: HorizontalBox {
                // alignment: center;
                for source in row: Rectangle {
                    height: 100px;
                    // height: 200px;
                    background: ta.has-hover ? grey.transparentize(0.1) : grey;
                    border-radius: 8px;

                    border-width: source.uid == Bridge.selected-video-src ? 8px : 0px;
                    border-color: source.uid == Bridge.selected-video-src ? lightgreen : white;

                    ta := TouchArea {
                        mouse-cursor: self.has-hover ? pointer : default;

                        clicked() => {
                            if source.uid == Bridge.selected-video-src {
                                Bridge.selected-video-src = -1;
                            } else {
                                Bridge.selected-video-src = source.uid;
                            }
                        }
                    }

                    Image {
                        y: (parent.height - vl-video.height / 2) / 2;
                        source: @image-url("./video.svg");
                    }

                    vl-video := VerticalLayout {
                        Rectangle { }

                        Rectangle {
                            background: whitesmoke.transparentize(0.1);
                            height: 40px;

                            Text {
                                text: source.name;
                            }
                        }
                    }
                }
            }
        }

        if Bridge.is-audio-supported: HorizontalBox {
            alignment: space-between;
            Text {
                horizontal-alignment: center;
                text: "Audio";
                font-weight: 600;
            }

            Rectangle { /* Spacer */ }
        }

        if Bridge.is-audio-supported: VerticalBox {
            for row in Bridge.audio-sources: HorizontalBox {
                // alignment: center;
                for source in row: Rectangle {
                    height: 100px;
                    // width: (parent.width / row.length - parent.padding).min(250px); //  250px;
                    // width: ((parent.width - parent.padding) / row.length).min(250px); //  250px;
                    background: ta-aud.has-hover ? grey.transparentize(0.1) : grey;
                    border-radius: 8px;

                    border-width: source.uid == Bridge.selected-audio-src ? 8px : 0px;
                    border-color: source.uid == Bridge.selected-audio-src ? lightgreen : white;

                    ta-aud := TouchArea {
                        mouse-cursor: self.has-hover ? pointer : default;

                        clicked() => {
                            if source.uid == Bridge.selected-audio-src {
                                Bridge.selected-audio-src = -1;
                            } else {
                                Bridge.selected-audio-src = source.uid;
                            }
                        }
                    }

                    Image {
                        y: (parent.height - vl-audio.height / 2) / 2;
                        source: @image-url("./audio.svg");
                    }

                    vl-audio := VerticalLayout {
                        Rectangle { }

                        Rectangle {
                            background: whitesmoke.transparentize(0.1);
                            height: 40px;

                            Text {
                                overflow: TextOverflow.clip;
                                text: source.name;
                            }
                        }
                    }
                }
            }
        }

        // if Bridge.selected-audio-src == -1 && Bridge.selected-video-src == -1: Text {
        //     horizontal-alignment: center;
        //     text: "At least one source is required to start casting";
        // }

        // if Bridge.selected-audio-src != -1 || Bridge.selected-video-src != -1: Button {
        Button {
            enabled: Bridge.selected-audio-src != -1 || Bridge.selected-video-src != -1;
            text: "Start";
            clicked => {
                Bridge.start-cast(Bridge.selected-video-src, Bridge.selected-audio-src);
            }
        }
    }
}

component StartingCastView inherits Rectangle {
    width: vb.preferred-width;
    height: vb.preferred-height;

    vb := VerticalBox {
        Spinner {
            indeterminate: true;
        }

        Text {
            text: "Starting";
            horizontal-alignment: center;
            font-weight: 600;
        }

        Button {
            text: "Cancel";
            clicked => Bridge.stop-cast();
        }
    }
}

component CastingView inherits Rectangle {
    height: vb.preferred-height;

    vb := VerticalBox {
        Text {
            horizontal-alignment: center;
            text: "Casting to " + Bridge.device-name;
        }

        Button {
            text: "Stop casting";
            clicked => Bridge.stop-cast();
        }
    }
}

export component MainWindow inherits Window {
    title: "FCast Sender";

    preferred-width: 800px;
    preferred-height: 500px;

    if Bridge.app-state == AppState.Disconnected: ConnectView {
        width: root.width.min(500px);
        height: root.height.min(500px);
    }

    if Bridge.app-state == AppState.Connecting: ConnectingView { }

    if Bridge.app-state == AppState.UnsupportedReceiver: UnsupportedReceiverView { }

    if Bridge.app-state == AppState.SelectingSource: SelectSourceView {
        width: root.width.min(900px);
    }

    if Bridge.app-state == AppState.StartingCast: StartingCastView { }

    if Bridge.app-state == AppState.Casting: CastingView {
        width: root.width.min(900px);
    }
}
