use anyhow::{bail, Result};
use camino::Utf8PathBuf;
use clap::{Args, Subcommand};
use xshell::{cmd, Shell};

use crate::{sh, workspace};

/// The exact flutter_rust_bridge version the plugin is built against.
///
/// The codegen binary, the `flutter_rust_bridge` Dart package, the
/// `flutter_rust_bridge_hooks` build hook, and the plugin's Rust crate must
/// all carry this version (a mismatch fails at app startup). A codegen binary
/// rewrites the manifest pins to its own version when it runs, so the pins
/// are re-asserted from this constant instead of trusting the manifests
/// (which is how a stray 2.12.0 run once downgraded them).
const FRB_VERSION: &str = "2.13.0-beta.5";

#[derive(Subcommand)]
pub enum FlutterCommand {
    /// Regenerate the flutter_rust_bridge + freezed bindings for the Flutter
    /// plugin at `sdk/sender/flutter-plugin`.
    ///
    /// The generated files (`lib/src/rust/*.dart`, `rust/src/frb_generated.rs`)
    /// are git-ignored; run this after a fresh checkout, after editing
    /// `rust/src/api.rs`, and in CI before `flutter pub publish`.
    Generate {
        /// Comma-separated cargo features to generate bindings for. Must match
        /// the features the app builds with (see the plugin's `hook/build.dart`
        /// and README). Defaults to everything.
        #[clap(long, default_value = "fcast,chromecast,logging")]
        features: String,
    },
}

#[derive(Args)]
pub struct FlutterArgs {
    #[clap(subcommand)]
    pub cmd: FlutterCommand,
}

impl FlutterArgs {
    pub fn run(self) -> Result<()> {
        match self.cmd {
            FlutterCommand::Generate { features } => generate(&features),
        }
    }
}

fn plugin_dir() -> Result<Utf8PathBuf> {
    Ok(workspace::root_path()?.join("sdk/sender/flutter-plugin"))
}

fn generate(features: &str) -> Result<()> {
    let sh = sh();
    let _p = sh.push_dir(plugin_dir()?);

    // Repair any pin drift (e.g. from a stray manual codegen run) before
    // resolving dependencies.
    enforce_frb_pins(&sh)?;

    println!("Generating bindings for features [{features}] with codegen {FRB_VERSION}");

    let codegen = codegen_binary(&sh)?;

    cmd!(sh, "flutter pub get").run()?;
    cmd!(sh, "{codegen} generate --rust-features {features}").run()?;
    cmd!(
        sh,
        "flutter pub run build_runner build --delete-conflicting-outputs"
    )
    .run()?;

    // The enforced binary rewrites the pins with its own (correct) version,
    // so drift here means a different codegen ran and the generated files are
    // suspect. Fail loudly instead of repairing silently.
    if let Some(file) = drifted_manifest(&sh)? {
        bail!(
            "{file} no longer pins flutter_rust_bridge {FRB_VERSION} after codegen. The \
             bindings were generated by the wrong codegen version and must be regenerated."
        );
    }

    println!("Bindings regenerated.");
    Ok(())
}

/// Absolute path to the version-pinned codegen binary, installed under the
/// workspace `target/` directory on first use.
///
/// Deliberately NOT resolved from `PATH`: dev machines often carry another
/// frb codegen version, and running that one silently rewrites the manifest
/// pins to its own version. The install directory is version-addressed, so
/// bumping [`FRB_VERSION`] installs the new codegen automatically.
fn codegen_binary(sh: &Shell) -> Result<Utf8PathBuf> {
    let root = workspace::root_path()?
        .join("target/frb-codegen")
        .join(FRB_VERSION);
    let bin = root.join(if cfg!(windows) {
        "bin/flutter_rust_bridge_codegen.exe"
    } else {
        "bin/flutter_rust_bridge_codegen"
    });
    if !bin.exists() {
        cmd!(
            sh,
            "cargo install flutter_rust_bridge_codegen --version ={FRB_VERSION} --locked --root {root}"
        )
        .run()?;
    }
    Ok(bin)
}

/// Rewrite the plugin manifests' flutter_rust_bridge pins to [`FRB_VERSION`],
/// reporting anything that had drifted.
fn enforce_frb_pins(sh: &Shell) -> Result<()> {
    rewrite_pin(sh, "pubspec.yaml", "flutter_rust_bridge:", FRB_VERSION)?;
    rewrite_pin(
        sh,
        "pubspec.yaml",
        "flutter_rust_bridge_hooks:",
        FRB_VERSION,
    )?;
    rewrite_pin(
        sh,
        "rust/Cargo.toml",
        "flutter_rust_bridge =",
        &format!("\"={FRB_VERSION}\""),
    )?;
    Ok(())
}

/// Set the value of the manifest line starting with `key` (module-level or
/// indented) to `value`, preserving indentation. Missing keys are an error so
/// a manifest refactor can't silently disable the pin.
fn rewrite_pin(sh: &Shell, file: &str, key: &str, value: &str) -> Result<()> {
    let content = sh.read_file(file)?;
    let mut lines = Vec::new();
    let mut found = false;
    let mut changed = false;
    for line in content.lines() {
        let trimmed = line.trim_start();
        if let Some(current) = trimmed.strip_prefix(key) {
            found = true;
            let current = current.trim();
            if current != value {
                println!("{file}: repinning `{key}` from {current} to {value}");
                let indent = &line[..line.len() - trimmed.len()];
                lines.push(format!("{indent}{key} {value}"));
                changed = true;
                continue;
            }
        }
        lines.push(line.to_string());
    }
    if !found {
        bail!("could not find `{key}` in {file} to pin it to {value}");
    }
    if changed {
        sh.write_file(file, lines.join("\n") + "\n")?;
    }
    Ok(())
}

/// The first manifest whose flutter_rust_bridge pin no longer reads
/// [`FRB_VERSION`], if any.
fn drifted_manifest(sh: &Shell) -> Result<Option<&'static str>> {
    for (file, needle) in [
        (
            "pubspec.yaml",
            format!("flutter_rust_bridge: {FRB_VERSION}"),
        ),
        (
            "rust/Cargo.toml",
            format!("flutter_rust_bridge = \"={FRB_VERSION}\""),
        ),
    ] {
        if !sh.read_file(file)?.contains(&needle) {
            return Ok(Some(file));
        }
    }
    Ok(None)
}
