// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { FluentFontSettings, FluentPalette, FCastPalette } from "styling.slint";
import { FocusBorder } from "components.slint";

export component Button {
    in property <string> text;
    in property <image> icon;
    in property <length> icon-size: 20px;
    in property <bool> primary;
    in property <bool> enabled <=> i-touch-area.enabled;
    in property <bool> checkable;
    in property <bool> colorize-icon;
    out property <bool> has-focus: i-focus-scope.has-focus;
    out property <bool> pressed: self.enabled && i-touch-area.pressed;
    in-out property <bool> checked;

    callback clicked;

    private property <brush> text-color: primary || checked ? FluentPalette.accent-foreground : FluentPalette.control-foreground;

    // min-width: max(32px, i-layout.min-width);
    min-width: max(36px, i-layout.min-width);
    min-height: max(36px, i-layout.min-height);
    horizontal-stretch: 0;
    vertical-stretch: 0;
    forward-focus: i-focus-scope;

    accessible-role: button;
    accessible-enabled: root.enabled;
    accessible-checkable: root.checkable;
    accessible-checked: root.checked;
    accessible-label: root.text;
    accessible-action-default => { i-touch-area.clicked(); }

    states [
        disabled when !root.enabled : {
            root.text-color: FCastPalette.button-disabled-text-color;
            i-background.background: FCastPalette.button-pressed-background;
            i-background.drop-shadow-color: FCastPalette.button-pressed-drop-shadow-color;
            i-border.border-color: FCastPalette.button-pressed-border-color;
        }
        pressed when root.pressed : {
            root.text-color: root.primary || root.checked ? FluentPalette.text-accent-foreground-secondary : FluentPalette.text-secondary;
            i-background.background: FCastPalette.button-pressed-background;
            i-background.drop-shadow-color: FCastPalette.button-pressed-drop-shadow-color;
            i-border.border-color: FCastPalette.button-pressed-border-color;
        }
        hover when i-touch-area.has-hover : {
            i-background.background: FCastPalette.button-hover-background;
            i-background.drop-shadow-color: FCastPalette.button-hover-drop-shadow-color;
            i-border.border-color: FCastPalette.button-hover-border-color;
        }
        checked when root.checked : {
            i-background.background: FluentPalette.accent-background;
            i-border.border-color: FluentPalette.accent-control-border;
            root.text-color: FluentPalette.accent-foreground;
        }
    ]

    i-background := Rectangle {
        // Circle when icon only
        border-radius: root.text == "" ? self.height : 6px;

        background: FCastPalette.button-default-background;
        drop-shadow-color: FCastPalette.button-default-drop-shadow-color;

        animate border-color { duration: 150ms; }
        // animate background, border-color { duration: 150ms; }
        i-border := Rectangle {
            border-radius: parent.border-radius;
            border-width: 1px;

            border-color: FCastPalette.button-default-border-color;

            animate border-color { duration: 50ms; }
        }

        i-layout := HorizontalLayout {
            padding-left: 12px;
            padding-right: 12px;
            padding-top: 5px;
            padding-bottom: 5px;
            spacing: 4px;
            alignment: center;

            if (root.icon.width > 0 && root.icon.height > 0) : Image {
                y: (parent.height - self.height) / 2;
                source <=> root.icon;
                width: root.icon-size;
                min-height: root.icon-size;
                colorize: root.colorize-icon ? root.text-color : transparent;
            }

            if (root.text != ""): Text {
                font-size: FluentFontSettings.body.font-size;
                font-weight: FluentFontSettings.body.font-weight;
                horizontal-alignment: center;
                vertical-alignment: center;
                text: root.text;
                color: root.text-color;
                // animate color { duration: 150ms; }
                accessible-role: none;
            }
        }
    }

    i-touch-area := TouchArea {
        // mouse-cursor: pointer;

        clicked => {
            if (root.checkable) {
                root.checked = !root.checked;
            }
            root.clicked();
        }
    }

    i-focus-scope := FocusScope {
        x: 0;
        width: 0; // Do not react on clicks
        enabled <=> root.enabled;

        key-pressed(event) => {
            if (event.text == " " || event.text == "\n") {
                i-touch-area.clicked();
                 return accept;
            }

            return reject;
        }
    }

    // focus border
    if (root.has-focus && root.enabled) : FocusBorder {
        border-radius: i-background.border-radius;
    }
}
