// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

// cSpell: ignore standardbutton

export { StyleMetrics, ScrollView, Button, Palette } from "std-widgets-impl.slint";

export { CheckBox } from "checkbox.slint";
export { ComboBox } from "combobox.slint";
export { LineEdit } from "lineedit.slint";
export { ListView, StandardListView } from "listview.slint";
export { ProgressIndicator } from "progressindicator.slint";
export { Slider } from "slider.slint";
export { Spinner } from "spinner.slint";
export { Switch } from "switch.slint";
export { TextEdit } from "textedit.slint";

import { Palette } from "std-widgets-impl.slint";
import { FCastPalette } from "styling.slint";

export component FText inherits Text {
    color: Palette.foreground;
}

export global Icons {
    out property <image> tv: @image-url("icons/tv.svg");
    out property <image> arrow-down: @image-url("icons/down.svg");
    out property <image> arrow-right: @image-url("icons/arrow_right.svg");
    out property <image> open-external: @image-url("icons/open-external.svg");
    out property <image> disconnect: @image-url("icons/disconnect-icon.svg");
    out property <image> link: @image-url("icons/link.svg");
    out property <image> folder-fcast: @image-url("icons/folder-fcast.svg");
    out property <image> mirror: @image-url("icons/mirror-fcast.svg");
    out property <image> media-file: @image-url("icons/media-file-fcast.svg");
    out property <image> play: @image-url("icons/play.svg");
    out property <image> pause: @image-url("icons/pause.svg");
    out property <image> settings: @image-url("icons/settings.svg");
    out property <image> playback-rate: @image-url("icons/playback_rate.svg");
    out property <image> close: @image-url("icons/close.svg");
    out property <image> upload: @image-url("icons/upload.svg");
    out property <image> dev-log: @image-url("icons/dev-log.svg");
    out property <image> fcast: @image-url("icons/fcast-icon.png");
    out property <image> background: @image-url("icons/background-img.png");
    out property <image> fcast-small: @image-url("icons/fcast-small.svg");
    out property <image> gcast-small: @image-url("icons/gcast-small.svg");
    out property <image> img: @image-url("icons/image.svg");
    out property <image> video: @image-url("icons/video.svg");
    out property <image> audio: @image-url("icons/audio.svg");
    out property <image> arrow-turn-up: @image-url("icons/arrow-turn-up.svg");
    out property <image> stop: @image-url("icons/stop.svg");
    out property <image> check-tick: @image-url("icons/check-tick.svg");
    out property <image> info: @image-url("icons/info.svg");
    out property <image> volume-high: @image-url("icons/volume-high.svg");
    out property <image> clipboard: @image-url("icons/clipboard.svg");
    out property <image> more: @image-url("icons/more.svg");
}

export component Spacer inherits Rectangle { }

component Circle inherits Rectangle {
    height: self.width;
    border-width: 1.22px;
    border-radius: self.height;
    border-color: red;
}

component LabelText inherits Text {
    color: Palette.foreground;
    font-weight: 500;
    font-size: 20px;
}

component SecondaryText inherits Text {
    color: FCastPalette.neutral-600;
    font-weight: 300;
    font-size: 12px;
}

export component NoReceiverFound {
    HorizontalLayout {
        Spacer { }

        VerticalLayout {
            alignment: center;
            spacing: 10px;

            Circle {
                width: 25%;
                border-color: FCastPalette.border-secondary.transparentize(94%);

                Circle {
                    width: 75%;
                    border-color: FCastPalette.border-secondary.transparentize(90%);

                    Circle {
                        width: 70%;
                        border-color: FCastPalette.border-secondary.transparentize(85%);

                        Circle {
                            width: 60%;
                            border-color: FCastPalette.border-secondary.transparentize(80%);
                        }
                    }
                }
            }

            LabelText {
                horizontal-alignment: center;
                text: "No receivers found";
            }

            SecondaryText {
                text: "FCast requires a Receiver App running on your target device before it appears here.";
                horizontal-alignment: center;
                wrap: word-wrap;
            }
        }

        Spacer { }
    }
}
