import { Icons, FText, Button, } from "../../../../../senders/ui-components/std-widgets.slint";
import { Bridge, UiMode } from "../globals.slint";
import { PositionScrubber, ProgressLabels, MasterButton, ScrubbyMcScrub, VolumePreview } from "../common.slint";
import { FCastPalette } from "../../../../../senders/ui-components/styling.slint";

component PlaylistControlButton inherits Button {
    in property <bool> previous: false;

    width: 48px;
    height: 48px;
    icon: Icons.playlist-next;
    icon-rotation: previous ? 180deg : 0deg;
    colorize-icon: true;
    icon-size: 15px;
    background-default-color: @linear-gradient(133.14deg, rgba(52, 52, 52, 0.1) 6.7%, rgba(20, 20, 20, 0.1) 92.77%);

    clicked => {
        Bridge.select-playlist-item(Bridge.playlist-idx + (previous ? -1 : 1));
    }
}

export component AudioPlayerView inherits Rectangle {
    background: FCastPalette.neutral-1100;

    property <bool> small-mode: root.height <= (500px +  (Bridge.media-title.is-empty ? 0px : 35px) + (Bridge.artist-name.is-empty ? 0px : 25px));

    Image {
        image-fit: cover;
        source: Bridge.blured-audio-track-cover.img;
        width: 100%;
        height: 100%;
        transform-rotation: Bridge.blured-audio-track-cover.rotation;
    }

    if Bridge.blured-audio-track-cover.img.width > 0: Rectangle {
        background: Bridge.controls-bg-gradient;
    }

    VerticalLayout {
        padding: !small-mode ? 58px : 10px;
        padding-bottom: 20px;
        spacing: 5px;
        alignment: center;

        if root.height > 300px: HorizontalLayout {
            alignment: center;

            pure function thumbnail-size() -> length {
                let width = Math.min(root.width * (!small-mode ? 35% : 10%), 400px);
                let height = Math.min(root.height * (!small-mode ? 50% : 20%), 550px);
                Math.min(width, height)
            }

            Rectangle {
                width: thumbnail-size();
                height: self.width;
                border-radius: 4px;
                background: Bridge.audio-track-cover.img.width == 0 ? FCastPalette.neutral-1000 : transparent;

                if Bridge.audio-track-cover.img.width > 0: Image {
                    source: Bridge.audio-track-cover.img;
                    image-fit: contain;
                    width: parent.width;
                    height: parent.height;
                    transform-rotation: Bridge.audio-track-cover.rotation;
                }

                if Bridge.audio-track-cover.img.width == 0: Image {
                    source: Icons.music-note;
                    width: parent.width * 50%;
                    height: parent.height * 52%;
                }
            }
        }

        Rectangle {
            height: !small-mode ? 43px : 5px;
        }

        if !Bridge.media-title.is-empty: FText {
            horizontal-alignment: center;
            text: Bridge.media-title;
            font-size: 28px;
            font-weight: 600;
            color: FCastPalette.neutral-100;
        }

        if !Bridge.artist-name.is-empty: FText {
            horizontal-alignment: center;
            text: Bridge.artist-name;
            font-size: 18px;
            font-weight: 600;
            color: FCastPalette.opacity-light-500;
        }

        Rectangle {
            height: 20px;
        }

        ScrubbyMcScrub { }

        if Bridge.ui-mode == UiMode.Full: HorizontalLayout {
            alignment: center;
            spacing: 30px;

            VerticalLayout {
                visible: Bridge.playlist-idx != 0 && Bridge.playlist-length != 0;
                alignment: center;

                PlaylistControlButton {
                    previous: true;
                }
            }

            MasterButton { }

            VerticalLayout {
                visible: Bridge.playlist-idx < Bridge.playlist-length - 1;
                alignment: center;

                PlaylistControlButton { }
            }
        }
    }

    VolumePreview {
        width: 100%;
        height: 100%;
    }
}
