[package]
name = "terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
fcast-sender-sdk = { path = "../../fcast-sender-sdk" }
env_logger.workspace = true
log.workspace = true
tokio.workspace = true