[package]
name = "terminal"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
fcast-sender-sdk = { path = "../../fcast-sender-sdk", default-features = false, features = ["fcast", "chromecast"] }
env_logger.workspace = true
log.workspace = true
tokio.workspace = true